SRCDIR = src
OBJDIR = obj
BINDIR = bin

SRC_FILES := $(wildcard $(SRCDIR)/*.c)
OBJECTS :=  $(SRC_FILES:$(SRCDIR)/%.c=$(OBJDIR)/%.o)
rm = rm -f

CC = emcc
COMPILER_FLAGS = -std=c99 -Wall -Iheader -s USE_SDL=2 -s USE_SDL_TTF=2 -O2
LINKER = emcc -o
LINKER_FLAGS = -Wall -Iheader -s USE_SDL=2 -s USE_SDL_TTF=2 -werror -s ASSERTIONS=1 -s SAFE_HEAP=1 --preload-file res/ -O2
TARGET = ga-stardew.html


$(BINDIR)/$(TARGET): $(OBJECTS)
	$(LINKER) $@ $(LINKER_FLAGS) $(OBJECTS)
	echo "Linking Complete!"

$(OBJECTS): $(OBJDIR)/%.o : $(SRCDIR)/%.c
	$(CC) $(COMPILER_FLAGS) -c $< -o $@
	echo "Compiled "$<" successfully!"

clean:
	$(rm) $(OBJECTS)
	echo "Cleanup complete!"

remove:
	make clean
	$(rm) $(BINDIR)/ga-stardew.html
	$(rm) $(BINDIR)/ga-stardew.data
	$(rm) $(BINDIR)/ga-stardew.js
	echo "Executable removed!"
